### ISSUE TITLE
I need some assistance please 

### ISSUE THREAD

**Issue by juancarlosfield** [learn-co-curriculum/debugging-errors-readme#11]
Since yesterday I have been trying to get in touch with someone that knows about the assignment: https://learn.co/tracks/web-development-fundamentals/intro-to-ruby/variables-and-methods/introductory-default-arguments-2

**Comment by AnnJohn** [comment]
hi @juancarlosfield you can use the Ask a Question tool. If you're a Learn Verified student, the response time is usually very quick but since you're in the public pre-work, the response time will be much longer. 

Unfortunately we use this space for issues on the curriculum content and cannot help students individually with their issues with the code. Please check out learn.co/verified for more info on our program.

**Comment by juancarlosfield** [comment]
Dear AnnJohn;

Thank you for writing about this concern. I was a little confused with some
definitions so I decided to use the "Ask a question" button last Saturday
at 7:49pm. Fortunately, I got a response by Monday afternoon, which lead me
to re-schedule my second appointment (_I applied for the Fellowship that
starts in June 06, 2016._ ) with Jeff for this Thursday the 12th at 3:30pm
to May 31st at 6:30pm with Steven Nunez. Like I mentioned to Amanda, I
totally understand and appreciate the bandwidth in order to guaranteed the
service of the app; More over that, I have always received great experience
at the campus, hence despite of the short staff to answer students
concerns, based on their assignments, again, I am sure Adam, and the team
are doing the best of their capabilities to ensure great results at the
Flatiron school.

I will be at the campus tomorrow morning working on my assignments. My
dream is to be part of the Fellowship for Web Development June 2016 and I
will ensure this with hard work.

Respectfully,
Jc
212-363-0533
